version: "3"

services:

  rollup-full-node:
    volumes:
       - full-node-data:/mnt/full-node:rw
       - l1-node-data:/mnt/l1-node:rw
       - l2-node-data:/mnt/l2-node:rw
    depends_on:
      - openethereum_l2
#      - geth_l1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8545:8545
    environment:
      - CLEAR_DATA_KEY=3
      - STARTUP_WAIT_TIMEOUT=30
      - OPCODE_WHITELIST_MASK
      - LOCAL_L1_NODE_PORT
      - LOCAL_L1_NODE_PERSISTENT_DB_PATH=/mnt/l1-node
      - L1_NODE_INFURA_NETWORK
      - L1_NODE_INFURA_PROJECT_ID
      - L1_NODE_WEB3_URL
      - L1_SEQUENCER_PRIVATE_KEY
      - L1_SEQUENCER_MNEMONIC
      - L1_EARLIEST_BLOCK
      - L1_TO_L2_TRANSACTION_PASSER_ADDRESS
      - L2_TO_L1_MESSAGE_RECEIVER_ADDRESS
      - L2_TO_L1_MESSAGE_FINALITY_DELAY_IN_BLOCKS
      - L2_RPC_SERVER_HOST
      - L2_RPC_SERVER_PORT
      - L2_RPC_SERVER_PERSISTENT_DB_PATH=/mnt/full-node/level
      - L2_WALLET_PRIVATE_KEY
      - L2_WALLET_MNEMONIC
      - L2_WALLET_PRIVATE_KEY_PATH=/mnt/l2-node/private_key.txt
      - L2_NODE_WEB3_URL=http://openethereum_l2:9545/
#      - LOCAL_L2_NODE_PERSISTENT_DB_PATH=/mnt/l2-node/

  openethereum_l2:
    volumes:
       - l2-node-data:/mnt/l2-node/l2:rw
    build:
      context: docker/openethereum
      dockerfile: Dockerfile
    environment:
      - VOLUME_PATH=/mnt/l2-node/l2
      - PORT=9545
      - PRIVATE_KEY_PATH_SUFFIX=/private_key.txt
      - PRIVATE_KEY=0x4d5db4107d237df6a3d58ee5f70ae63d73d7658d4026f2eefd2f204c81682cb7
    expose:
      - "9545"
    ports:
      - 9545:9545
#
#  geth_l1:
#    volumes:
#      - l1-node-data:/mnt/l1-node/l1
#    build:
#      context: docker/geth
#      dockerfile: Dockerfile
#    environment:
#      - VOLUME_PATH=/mnt/l1-node/l1
#    expose:
#      - "8545"

volumes:
  full-node-data:
  l1-node-data:
  l2-node-data:
