[parity]
chain = "rollup-fullnode.json"
base_path = "/tmp/parity0"

[network]
discovery = false
bootnodes = []
max_peers = 0

[rpc]
hosts = ["all"]
interface = "all"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8450
